/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The Elixir emulation engine.
 *
 * Usage from TypeScript:
 * ```typescript
 * import { Emulator } from '@hexcore/elixir';
 *
 * const emu = new Emulator({ arch: 'x86_64', max_instructions: 100000 });
 * const entry = emu.load(binaryBuffer);
 * const result = emu.run(entry, 0n);
 * console.log(result.kind); // 'exit', 'insn_limit', 'error', 'user'
 * emu.dispose();
 * ```
 */
export declare class Emulator {
  /** Create a new Emulator instance. */
  constructor(config: JsEmulatorConfig)
  /**
   * Load a binary into the emulator.
   * Returns the entry point address.
   */
  load(data: Buffer): bigint
  /**
   * Start emulation from the given address.
   * end=0 means run until stop() or until max_instructions is reached.
   */
  run(start: bigint, end: bigint): JsStopReason
  /** Stop emulation (can be called from another thread). */
  stop(): void
  /** Get the number of API calls logged. */
  getApiCallCount(): number
  /** Get the detailed API call log — one entry per hooked Win32 call. */
  getApiCalls(): Array<JsApiCall>
  /**
   * Read a register value.
   * reg_id: Unicorn register ID (e.g., UC_X86_REG_RAX = 19).
   */
  regRead(regId: number): bigint
  /** Write a register value. */
  regWrite(regId: number, value: bigint): void
  /** Read memory from the emulator. */
  memRead(addr: bigint, size: number): Buffer
  /** Write memory to the emulator. */
  memWrite(addr: bigint, data: Buffer): void
  /** Map a memory region. */
  memMap(addr: bigint, size: bigint, prot: number): void
  /** Attach an interceptor hook at the given address. */
  interceptorAttach(address: bigint): void
  /** Detach an interceptor hook at the given address. */
  interceptorDetach(address: bigint): void
  /** Get interceptor log count. */
  interceptorLogCount(): number
  /** Enable Stalker tracing. */
  stalkerFollow(): void
  /** Disable Stalker tracing. */
  stalkerUnfollow(): void
  /** Get Stalker block count. */
  stalkerBlockCount(): number
  /** Export Stalker coverage as DRCOV format. */
  stalkerExportDrcov(): Buffer
  /** Save a snapshot of the current emulation state. */
  snapshotSave(): Buffer
  /** Restore from a snapshot. */
  snapshotRestore(blob: Buffer): void
  /** Release emulator resources. The emulator cannot be used after this call. */
  dispose(): void
  /** Check if the emulator has been disposed. */
  get isDisposed(): boolean
  /** Get the maximum instruction limit. */
  get maxInstructions(): number
  /** Set the maximum instruction limit. */
  set maxInstructions(value: number)
}

/**
 * Interceptor for hooking function calls.
 *
 * Usage from TypeScript:
 * ```typescript
 * const interceptor = new Interceptor(emulator);
 * interceptor.attach(0x401000n);
 * // ... run emulation ...
 * interceptor.detach(0x401000n);
 * ```
 */
export declare class Interceptor {
  /**
   * Create a new Interceptor attached to an Emulator.
   * Note: The Emulator must outlive the Interceptor.
   */
  constructor(emulator: Emulator)
  /**
   * Attach a hook at the given address.
   * This is a convenience method that delegates to Emulator.interceptor_attach().
   */
  attach(emulator: Emulator, address: bigint): void
  /** Detach a hook at the given address. */
  detach(emulator: Emulator, address: bigint): void
  /** Release interceptor resources. */
  dispose(): void
  /** Check if the interceptor has been disposed. */
  get isDisposed(): boolean
}

/**
 * Stalker for code coverage and tracing.
 *
 * Usage from TypeScript:
 * ```typescript
 * const stalker = new Stalker(emulator);
 * stalker.follow();
 * // ... run emulation ...
 * stalker.unfollow();
 * const drcov = stalker.exportDrcov();
 * ```
 */
export declare class Stalker {
  /** Create a new Stalker attached to an Emulator. */
  constructor(emulator: Emulator)
  /** Start following code execution. */
  follow(emulator: Emulator): void
  /** Stop following code execution. */
  unfollow(emulator: Emulator): void
  /** Get the number of basic blocks traced. */
  blockCount(emulator: Emulator): number
  /**
   * Drain traced events (returns empty for now, use exportDrcov instead).
   * TODO: Implement block event iteration when API is available.
   */
  drain(emulator: Emulator): Array<JsStalkerEvent>
  /** Export coverage data in DRCOV format. */
  exportDrcov(emulator: Emulator): Buffer
  /** Release stalker resources. */
  dispose(): void
  /** Check if the stalker has been disposed. */
  get isDisposed(): boolean
}

export declare function getVersion(): string

/**
 * A single API call record.
 *
 * Shape matches the `ApiCall` type consumed by the TS wrapper in
 * extensions/hexcore-elixir/src/extension.ts — the IDE reads each field
 * directly, so any rename here must be mirrored there (and vice versa).
 */
export interface JsApiCall {
  /** Function name (e.g. "GetSystemTimeAsFileTime"). */
  name: string
  /** Source DLL declared in the PE import table (empty for dynamic stubs). */
  module: string
  /** Stub address where the hook fired (a.k.a. pc). */
  address: bigint
  /** Value the handler returned (also what RAX held on return). */
  returnValue: bigint
  /**
   * First N argument registers captured at hook time.
   * N = 6 today (rcx, rdx, r8, r9, stack[0], stack[1]).
   * Entries past the real arity of the called function are noise — the
   * engine has no per-API signature table — consumers should trim based
   * on their own knowledge of the import.
   */
  arguments: Array<bigint>
}

/** Configuration for creating an Emulator instance. */
export interface JsEmulatorConfig {
  /** Target architecture: "x86_64", "x86", "arm", "arm64" */
  arch: string
  /** Target OS: "linux", "windows", "macos", "bare" */
  os?: string
  /** Maximum instructions for run() (0 = unlimited, use with caution) */
  maxInstructions?: number
  /** Stack size in bytes (default: 2MB) */
  stackSize?: number
  /** Heap size in bytes (default: 16MB) */
  heapSize?: number
  /** Enable permissive memory mode (auto-map on fault) */
  permissiveMemory?: boolean
  /** Enable verbose logging */
  verbose?: boolean
}

/** A single Stalker basic block event. */
export interface JsStalkerEvent {
  /** Block start address */
  from: bigint
  /** Block end address */
  to: bigint
  /** Execution count */
  count: number
}

/** Result of a run() operation. */
export interface JsStopReason {
  /** Stop reason kind: "exit", "insn_limit", "error", "user", "none" */
  kind: string
  /** Current instruction pointer address */
  address: bigint
  /** Number of instructions executed */
  instructionsExecuted: number
  /** Error message (if any) */
  message: string
}

/** Restore emulator state from a snapshot. */
export declare function snapshotRestore(emulator: Emulator, blob: Buffer): void

/**
 * Save a snapshot of the emulator state.
 * Returns a Buffer containing the serialized state.
 */
export declare function snapshotSave(emulator: Emulator): Buffer
